### ISSUE TITLE
Create updates directory

### ISSUE THREAD

**Issue by mpalmi** [pgaudit/set_user#16]
To facilitate future releases/decrease possibility of error in updating, we should move toward using an `updates` directory and wildcards.

Also try to automatically pull EXTNAME and EXTVERSION from the control file, rather than having to hardcode it every time.

See: https://github.com/pgpartman/pg_partman/blob/master/Makefile for examples of all of the above.

**Comment by mpalmi** [comment]
Probably won't be doing this anytime soon. Going to close out the Issue for now.

**Comment by keithf4** [comment]
Re-opening this issue. Should just be able to do this in a patch release.

**Comment by keithf4** [comment]
This was done
