### ISSUE TITLE
set/reset with token is useless

### ISSUE THREAD

**Issue by pkit** [pgaudit/set_user#22]
`select set_user('user1', 'secret'); select current_user; reset user;` = success

**Comment by mpalmi** [comment]
@pkit Apologies for the late reply. I'm just seeing this. We're going to get this patched up right away. Thanks for opening the ticket.

**Comment by mpalmi** [comment]
@pkit This issue is resolved by https://github.com/pgaudit/set_user/commit/1096551b47c7902290fd1b3c0d95fb9c5412ab7a

We're going to go ahead and tag a new release (stay tuned), with this change. Thanks again for pointing it out!
