### ISSUE TITLE
Superuser auditing improvements

### ISSUE THREAD

**Issue by JMLessard** [pgaudit/set_user#3]
When a superuser connect or a user escalate its privileges (set role) to superuser, the current pgaudit.log should be overiden to all automatically.
Something similar to AUDIT_SYS_OPERATIONS=TRUE in Oracle.
Any attempt to change the pgaudit parameters of the session should be rejected and logged.
A parameter, e.g., pgaudit.log_superuser_statements=on|off may enable this feature.

The setuser extension make something equivalent by calling set_role('therole') instead of SET ROLE.
But, the set_user() is by passed when you connect as a superuser.
I aggree that we can tighten controls (revoke superuser login and instead grant exec on set_user()),
but the question that kills is: What if someone by pass the controls? Are every superuser operations audited?
We deal with such issues with DOJ auditors when our product had been approved on other commercial RDBMS.
Integrating such feature into pgaudit would be great.

**Comment by jconway** [comment]
If you have followed the directions there is no way to bypass set_user and become superuser unless you stop postgres and restart it in single user mode. You should set up an external monitoring system to alert for all postgres restarts.

**Comment by JMLessard** [comment]
True, I agree, but auditor does not always agree on what we feel common sens.
Here is a test case where you can go incogito.
- set_user('postges');
- create role bestbody login password 'bestbody' superuser;
- psql -U bestbody
- set pgaudit.log='none'; <--by the way disabling logging is not audited (log=MISC) at all. pgaudit look like catching the statements once executed, so in that case when log=none.

I agree that creating a superuser is severe violation of security that must be sanction, but tracing what was done as superuser fall under another scope.

**Comment by jconway** [comment]
set_user() turns on log_statement = all, and prevents even superuser from changing it if configured. So the CREATE ROLE gets logged. If you are worried about this scenario, alert on CREATE ROLE.

**Comment by jconway** [comment]
The SET pgaudit.x statement also gets logged and could be alerted on

**Comment by mucahityavuz** [comment]
Hi,
running 
_set pgaudit.log='none';_
is not logged, so is there a way to log or prevent this action?
