### ISSUE TITLE
How to configure on Windows

### ISSUE THREAD

**Issue by NishchayDBA** [pgaudit/set_user#31]
Hi Team,

I would like to configure set_user extension on my Windows PGSQL 9.6 64 bit. Please help me with the correct steps as the Readme document have no more details about configuration on Windows.

Apologies for raising this request as an issue. Please guide me if this is the wrong approach.

**Comment by xetter9** [comment]
Hi @NishchayDBA, did you managed to find the solution to configure on Windows?

**Comment by NishchayDBA** [comment]
> Hi @NishchayDBA, did you managed to find the solution to configure on Windows?

Hi @xetter9, 

I have managed to install pgaudit extension on Windows by following these 2 links: 

1. https://github.com/njesp/build_pgaudit_on_windows
2. https://github.com/pgaudit/pgaudit/issues/66

**Comment by xetter9** [comment]
@NishchayDBA have you managed to configure the set_user extension on Windows?

**Comment by mpalmi** [comment]
Closing this out due to inactivity.
