### ISSUE TITLE
Annoying NOTICE messages about deprecated GUCs

### ISSUE THREAD

**Issue by CyberDem0n** [pgaudit/set_user#32]
Hi folks, first of all, I would like to thank you for a such great extension.

After the upgrade to REL2_0_0 the user experience changed a little bit.
We don't have any GUCs explicitly set in the config file (set_user is only added to the shared_preload_libraries), but every time when I connect to the database with psql and type `show <tab>` I get an annoying NOTICE message:
```
postgres=# show NOTICE:  set_user: deprecated GUC name "set_user.nosuperuser_target_whitelist"
HINT:  use "set_user.nosuperuser_target_allowlist" instead
NOTICE:  set_user: deprecated GUC name "set_user.superuser_whitelist"
HINT:  use "set_user.superuser_allowlist" instead
```

Can we do something about it?

**Comment by mpalmi** [comment]
Certainly. I'll look into this tomorrow. Sorry for the inconvenience.

**Comment by mpalmi** [comment]
@CyberDem0n Still looking into this. Turns out the deprecation is trickier than expected. I've got a rough cut at a fix. Will post once I've tested all the edge-cases. Thanks for opening the Issue and for your patience!

**Comment by CyberDem0n** [comment]
@mpalmi no problem, it is not urgent. Thank you for looking at it.

**Comment by mpalmi** [comment]
Fixed!

**Comment by CyberDem0n** [comment]
Nice, thank you @mpalmi!
