### ISSUE TITLE
2.0.1 fails to build against v14

### ISSUE THREAD

**Issue by devrimgunduz** [pgaudit/set_user#49]
Hi,

Getting these errors/warnings while trying to build 2.0.1 against PG14 beta3. Can you please take a look? Thanks! Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o set_user.o set_user.c
/usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o set_user.bc set_user.c
set_user.c: In function '_PG_init':
set_user.c:424:29: warning: assignment to 'ProcessUtility_hook_type' {aka 'void (*)(PlannedStmt *, const char *, _Bool,  ProcessUtilityContext,  struct ParamListInfoData *, QueryEnvironment *, struct _DestReceiver *, QueryCompletion *)'} from incompatible pointer type 'void (*)(PlannedStmt *, const char *, ProcessUtilityContext,  struct ParamListInfoData *, QueryEnvironment *, DestReceiver *, QueryCompletion *)' {aka 'void (*)(PlannedStmt *, const char *, ProcessUtilityContext,  struct ParamListInfoData *, QueryEnvironment *, struct _DestReceiver *, QueryCompletion *)'} [-Wincompatible-pointer-types]
  424 |         ProcessUtility_hook = PU_hook;
      |                             ^
In file included from set_user.c:51:
set_user.c: In function 'PU_hook':
compatibility.h:33:48: error: incompatible type for argument 4 of 'prev_hook'
   33 |         prev_hook(pstmt, queryString, context, params, queryEnv, dest, qc)
      |                                                ^~~~~~
      |                                                |
      |                                                ParamListInfo {aka struct ParamListInfoData *}
set_user.c:496:17: note: in expansion of macro '_prev_hook'
  496 |                 _prev_hook;
      |                 ^~~~~~~~~~
compatibility.h:33:48: note: expected 'ProcessUtilityContext' but argument is of type 'ParamListInfo' {aka 'struct ParamListInfoData *'}
   33 |         prev_hook(pstmt, queryString, context, params, queryEnv, dest, qc)
      |                                                ^~~~~~
set_user.c:496:17: note: in expansion of macro '_prev_hook'
  496 |                 _prev_hook;
      |                 ^~~~~~~~~~
compatibility.h:33:56: warning: passing argument 5 of 'prev_hook' from incompatible pointer type [-Wincompatible-pointer-types]
   33 |         prev_hook(pstmt, queryString, context, params, queryEnv, dest, qc)
      |                                                        ^~~~~~~~
      |                                                        |
      |                                                        QueryEnvironment *
set_user.c:496:17: note: in expansion of macro '_prev_hook'
  496 |                 _prev_hook;
      |                 ^~~~~~~~~~
compatibility.h:33:56: note: expected 'ParamListInfo' {aka 'struct ParamListInfoData *'} but argument is of type 'QueryEnvironment *'
   33 |         prev_hook(pstmt, queryString, context, params, queryEnv, dest, qc)
      |                                                        ^~~~~~~~
set_user.c:496:17: note: in expansion of macro '_prev_hook'
  496 |                 _prev_hook;
      |                 ^~~~~~~~~~
compatibility.h:33:66: warning: passing argument 6 of 'prev_hook' from incompatible pointer type [-Wincompatible-pointer-types]
   33 |         prev_hook(pstmt, queryString, context, params, queryEnv, dest, qc)
      |                                                                  ^~~~
      |                                                                  |
      |                                                                  DestReceiver * {aka struct _DestReceiver *}
set_user.c:496:17: note: in expansion of macro '_prev_hook'
  496 |                 _prev_hook;
      |                 ^~~~~~~~~~
compatibility.h:33:66: note: expected 'QueryEnvironment *' but argument is of type 'DestReceiver *' {aka 'struct _DestReceiver *'}
   33 |         prev_hook(pstmt, queryString, context, params, queryEnv, dest, qc)
      |                                                                  ^~~~
set_user.c:496:17: note: in expansion of macro '_prev_hook'
  496 |                 _prev_hook;
      |                 ^~~~~~~~~~
compatibility.h:33:72: warning: passing argument 7 of 'prev_hook' from incompatible pointer type [-Wincompatible-pointer-types]
   33 |         prev_hook(pstmt, queryString, context, params, queryEnv, dest, qc)
      |                                                                        ^~
      |                                                                        |
      |                                                                        QueryCompletion *
set_user.c:496:17: note: in expansion of macro '_prev_hook'
  496 |                 _prev_hook;
      |                 ^~~~~~~~~~
compatibility.h:33:72: note: expected 'DestReceiver *' {aka 'struct _DestReceiver *'} but argument is of type 'QueryCompletion *'
   33 |         prev_hook(pstmt, queryString, context, params, queryEnv, dest, qc)
      |                                                                        ^~
set_user.c:496:17: note: in expansion of macro '_prev_hook'
  496 |                 _prev_hook;
      |                 ^~~~~~~~~~
compatibility.h:33:9: error: too few arguments to function 'prev_hook'
   33 |         prev_hook(pstmt, queryString, context, params, queryEnv, dest, qc)
      |         ^~~~~~~~~
set_user.c:496:17: note: in expansion of macro '_prev_hook'
  496 |                 _prev_hook;
      |                 ^~~~~~~~~~
compatibility.h:36:66: error: incompatible type for argument 4 of 'standard_ProcessUtility'
   36 |         standard_ProcessUtility(pstmt, queryString,     context, params, queryEnv, dest, qc)
      |                                                                  ^~~~~~
      |                                                                  |
      |                                                                  ParamListInfo {aka struct ParamListInfoData *}
set_user.c:500:17: note: in expansion of macro '_standard_ProcessUtility'
  500 |                 _standard_ProcessUtility;
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from set_user.c:40:
/usr/pgsql-14/include/server/tcop/utility.h:87:95: note: expected 'ProcessUtilityContext' but argument is of type 'ParamListInfo' {aka 'struct ParamListInfoData *'}
   87 |                                                                         ProcessUtilityContext context, ParamListInfo params,
      |                                                                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
In file included from set_user.c:51:
compatibility.h:36:74: warning: passing argument 5 of 'standard_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
   36 |         standard_ProcessUtility(pstmt, queryString,     context, params, queryEnv, dest, qc)
      |                                                                          ^~~~~~~~
      |                                                                          |
      |                                                                          QueryEnvironment *
set_user.c:500:17: note: in expansion of macro '_standard_ProcessUtility'
  500 |                 _standard_ProcessUtility;
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from set_user.c:40:
/usr/pgsql-14/include/server/tcop/utility.h:87:118: note: expected 'ParamListInfo' {aka 'struct ParamListInfoData *'} but argument is of type 'QueryEnvironment *'
   87 |                                                                         ProcessUtilityContext context, ParamListInfo params,
      |                                                                                                        ~~~~~~~~~~~~~~^~~~~~
In file included from set_user.c:51:
compatibility.h:36:84: warning: passing argument 6 of 'standard_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
   36 |         standard_ProcessUtility(pstmt, queryString,     context, params, queryEnv, dest, qc)
      |                                                                                    ^~~~
      |                                                                                    |
      |                                                                                    DestReceiver * {aka struct _DestReceiver *}
set_user.c:500:17: note: in expansion of macro '_standard_ProcessUtility'
  500 |                 _standard_ProcessUtility;
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from set_user.c:40:
/usr/pgsql-14/include/server/tcop/utility.h:88:91: note: expected 'QueryEnvironment *' but argument is of type 'DestReceiver *' {aka 'struct _DestReceiver *'}
   88 |                                                                         QueryEnvironment *queryEnv,
      |                                                                         ~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from set_user.c:51:
compatibility.h:36:90: warning: passing argument 7 of 'standard_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
   36 |         standard_ProcessUtility(pstmt, queryString,     context, params, queryEnv, dest, qc)
      |                                                                                          ^~
      |                                                                                          |
      |                                                                                          QueryCompletion *
set_user.c:500:17: note: in expansion of macro '_standard_ProcessUtility'
  500 |                 _standard_ProcessUtility;
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from set_user.c:40:
/usr/pgsql-14/include/server/tcop/utility.h:89:87: note: expected 'DestReceiver *' {aka 'struct _DestReceiver *'} but argument is of type 'QueryCompletion *'
   89 |                                                                         DestReceiver *dest, QueryCompletion *qc);
      |                                                                         ~~~~~~~~~~~~~~^~~~
In file included from set_user.c:51:
compatibility.h:36:9: error: too few arguments to function 'standard_ProcessUtility'
   36 |         standard_ProcessUtility(pstmt, queryString,     context, params, queryEnv, dest, qc)
      |         ^~~~~~~~~~~~~~~~~~~~~~~
set_user.c:500:17: note: in expansion of macro '_standard_ProcessUtility'
  500 |                 _standard_ProcessUtility;
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from set_user.c:40:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: declared here
   85 | extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [<builtin>: set_user.o] Error 1
make[1]: *** Waiting for unfinished jobs....
set_user.c:424:22: warning: incompatible function pointer types assigning to 'ProcessUtility_hook_type' (aka 'void (*)(struct PlannedStmt *, const char *, bool, ProcessUtilityContext, struct ParamListInfoData *, struct QueryEnvironment *, struct _DestReceiver *, struct QueryCompletion *)') from 'void (PlannedStmt *, const char *, ProcessUtilityContext, ParamListInfo, QueryEnvironment *, DestReceiver *, QueryCompletion *)' (aka 'void (struct PlannedStmt *, const char *, ProcessUtilityContext, struct ParamListInfoData *, struct QueryEnvironment *, struct _DestReceiver *, struct QueryCompletion *)') [-Wincompatible-function-pointer-types]
        ProcessUtility_hook = PU_hook;
                            ^ ~~~~~~~
set_user.c:496:3: error: too few arguments to function call, expected 8, have 7
                _prev_hook;
                ^~~~~~~~~~
./compatibility.h:33:67: note: expanded from macro '_prev_hook'
        prev_hook(pstmt, queryString, context, params, queryEnv, dest, qc)
        ~~~~~~~~~                                                        ^
set_user.c:500:3: error: too few arguments to function call, expected 8, have 7
                _standard_ProcessUtility;
                ^~~~~~~~~~~~~~~~~~~~~~~~
./compatibility.h:36:81: note: expanded from macro '_standard_ProcessUtility'
        standard_ProcessUtility(pstmt, queryString,     context, params, queryEnv, dest, qc)
        ~~~~~~~~~~~~~~~~~~~~~~~                                                            ^
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: 'standard_ProcessUtility' declared here
extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
            ^
1 warning and 2 errors generated.

**Comment by devrimgunduz** [comment]
ping. v14 is around the corner.

**Comment by mpalmi** [comment]
@devrimgunduz Release v2.0.1 does not currently support pg14. Please take a look at the v3.0.0 tag for v14 support. The Release for that tag should be done shortly.

**Comment by devrimgunduz** [comment]
Hi @mpalmi , 

I need a tarball to build the RPMs, so I'll wait until you release 3.0.0. Thanks!

**Comment by mpalmi** [comment]
@devrimgunduz https://github.com/pgaudit/set_user/releases/tag/REL3_0_0
