### ISSUE TITLE
PostgreSQL 15 support

### ISSUE THREAD

**Issue by devrimgunduz** [pgaudit/set_user#66]
Hi,

I see that you've committed some fixes for PG 15 support. Can you  please release a new version, so that I can build RPMs against v15?

Thanks!

**Comment by keithf4** [comment]
We have an RC1 release for 4.x out now. Not sure if you want to build that out for a full release, but should at least now allow build testing.

**Comment by hunleyd** [comment]
this issue can be closed now that [4.0.0](https://github.com/pgaudit/set_user/releases/tag/REL4_0_0) is released
