### ISSUE TITLE
Allow role in superuser_whitelist

### ISSUE THREAD

**Issue by JMLessard** [pgaudit/set_user#7]
Would it be possible to specify a role in the superuser_whitelist so that role members can switch to superuser. 

Like the pg_hba.conf, role may have a plus sign prefix to make the difference with a user.
`# TYPE         DATABASE       USER                 ADDRESS         METHOD`
`host           all            +admin               0.0.0.0/0       md5`

**Comment by mpalmi** [comment]
Good suggestion. That is certainly doable. Expect an update soon.
